ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true  # بما أن الروبوت يتحرك على أرض مستوية
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # 1. إعدادات الـ Encoders (Odometry) القادمة من ESP32
    odom0: /odom
    odom0_config: [true,  true,  false, # X, Y, Z
                   false, false, true,  # Roll, Pitch, Yaw
                   true,  true,  false, # VX, VY, VZ
                   false, false, true,  # VRoll, VPitch, VYaw
                   false, false, false] # Ax, Ay, Az

    # # 2. إعدادات الـ IMU القادمة من ESP32
    # imu0: /imu/data
    # imu0_config: [false, false, false, # لا نحتاج للموقع من الـ IMU
    #               false, false, true,  # نأخذ الـ Yaw (التوجيه) فقط
    #               false, false, false,
    #               false, false, true,  # نأخذ السرعة الزاوية
    #               true,  true,  false] # نأخذ التسارع الخطي (X, Y)

    # imu0_remove_gravitational_acceleration: true