# NOTE: This config file is only for Node parameters; static transforms must be passed as arguments in the Launch file.

ekf_filter_node:
  ros__parameters:
    frequency: 50
    sensor_timeout: 0.1
    two_d_mode: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    odom0: /wheel/odom
    odom0_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, false]

    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, false]

    imu0_remove_gravitational_acceleration: true
